version: "3.3"

services: 

  service-one:
    image: uk.coders.service1:latest
    build: ./Service-1    
    ports:
      - 5001:8080

  service-two:
    image: uk.coders.service2:latest
    build:      
      context: ./Service-2
      dockerfile: Dockerfile
    volumes:
      - my_logs:/usr/src/app/log
    ports:
      - 5002:5000
    networks:
      - main
      
volumes:
  my_logs:

networks:
  main: