version: "3.7"

services: 

  service-one:
    build: ./Service-1    

  service-two:
    build:
      context: ./Service-2
      dockerfile: Dockerfile
    volumes:
      - my_logs:/usr/src/app/log
    ports:
      - 5002:5000
    networks:
      - main
      
volumes:
  my_logs:

networks:
  main: